"""
Matrix module.
"""
from __future__ import annotations
import _pathtracer.core.vector
__all__: list[str] = ['Matrix3', 'rotation_from_euler']
class Matrix3:
    def T(self) -> Matrix3:
        ...
    def __init__(self) -> None:
        ...
    def forward(self) -> _pathtracer.core.vector.Vector3:
        ...
    def right(self) -> _pathtracer.core.vector.Vector3:
        ...
    def transpose(self) -> Matrix3:
        ...
    def up(self) -> _pathtracer.core.vector.Vector3:
        ...
def rotation_from_euler(arg0: _pathtracer.core.vector.Vector3) -> Matrix3:
    ...
