"""
Vector module.
"""
from __future__ import annotations
import typing
__all__: list[str] = ['Color', 'Vector2', 'Vector3']
class Color:
    def __init__(self, r: typing.SupportsFloat | typing.SupportsIndex = 0.0, g: typing.SupportsFloat | typing.SupportsIndex = 0.0, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def b(self) -> float:
        ...
    def g(self) -> float:
        ...
    def r(self) -> float:
        ...
class Vector2:
    def __init__(self, x: typing.SupportsFloat | typing.SupportsIndex = 0.0, y: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def u(self) -> float:
        ...
    def v(self) -> float:
        ...
    def x(self) -> float:
        ...
    def y(self) -> float:
        ...
class Vector3:
    def __init__(self, x: typing.SupportsFloat | typing.SupportsIndex = 0.0, y: typing.SupportsFloat | typing.SupportsIndex = 0.0, z: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def u(self) -> float:
        ...
    def v(self) -> float:
        ...
    def w(self) -> float:
        ...
    def x(self) -> float:
        ...
    def y(self) -> float:
        ...
    def z(self) -> float:
        ...
