"""
Vector module.
"""
from __future__ import annotations
import _pathtracer.core.random
import typing
__all__: list[str] = ['Color', 'Vec2Core2', 'Vec3Core3', 'Vec3CoreColor', 'Vector2', 'Vector3', 'VectorBase2', 'VectorBase3', 'VectorBaseColor', 'cross', 'dot', 'random_on_hemisphere', 'random_unit_vector', 'reflect', 'refract']
class Color(Vec3CoreColor, VectorBaseColor):
    @staticmethod
    def black() -> Color:
        ...
    @staticmethod
    def blue() -> Color:
        ...
    @staticmethod
    def green() -> Color:
        ...
    @staticmethod
    def purple() -> Color:
        ...
    @staticmethod
    def red() -> Color:
        ...
    @staticmethod
    def teal() -> Color:
        ...
    @staticmethod
    def white() -> Color:
        ...
    @staticmethod
    def yellow() -> Color:
        ...
    def __init__(self, r: typing.SupportsFloat | typing.SupportsIndex = 0.0, g: typing.SupportsFloat | typing.SupportsIndex = 0.0, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def b(self) -> float:
        ...
    def g(self) -> float:
        ...
    def r(self) -> float:
        ...
class Vec2Core2(VectorBase2):
    pass
class Vec3Core3(VectorBase3):
    pass
class Vec3CoreColor(VectorBaseColor):
    pass
class Vector2(Vec2Core2):
    @typing.overload
    def __init__(self, e: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat | typing.SupportsIndex = 0.0, y: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def u(self) -> float:
        ...
    def v(self) -> float:
        ...
    def x(self) -> float:
        ...
    def y(self) -> float:
        ...
class Vector3(Vec3Core3):
    @typing.overload
    def __add__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __iadd__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __iadd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __imul__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __imul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __init__(self, e: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    @typing.overload
    def __init__(self, x: typing.SupportsFloat | typing.SupportsIndex = 0.0, y: typing.SupportsFloat | typing.SupportsIndex = 0.0, z: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __isub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __itruediv__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __itruediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __mul__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    def __repr__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    @typing.overload
    def __truediv__(self, arg0: Vector3) -> Vector3:
        ...
    @typing.overload
    def __truediv__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
        ...
    def as_array(self) -> typing.Annotated[list[float], "FixedSize(3)"]:
        ...
    def length(self) -> float:
        ...
    def u(self) -> float:
        ...
    def v(self) -> float:
        ...
    def w(self) -> float:
        ...
    def x(self) -> float:
        ...
    def y(self) -> float:
        ...
    def z(self) -> float:
        ...
class VectorBase2:
    pass
class VectorBase3:
    pass
class VectorBaseColor:
    pass
def cross(arg0: Vector3, arg1: Vector3) -> Vector3:
    ...
def dot(arg0: Vector3, arg1: Vector3) -> float:
    ...
def random_on_hemisphere(arg0: Vector3, arg1: _pathtracer.core.random.Generator) -> Vector3:
    ...
def random_unit_vector(arg0: _pathtracer.core.random.Generator) -> Vector3:
    ...
def reflect(arg0: Vector3, arg1: Vector3) -> Vector3:
    ...
def refract(arg0: Vector3, arg1: Vector3, arg2: typing.SupportsFloat | typing.SupportsIndex) -> Vector3:
    ...
