"""
Memory utils submodule.
"""
from __future__ import annotations
__all__: list[str] = ['CUDAMemInfo', 'get_cuda_meminfo', 'get_cuda_memory_free', 'get_cuda_memory_total', 'get_cuda_memory_used']
class CUDAMemInfo:
    def __init__(self) -> None:
        ...
    @property
    def free(self) -> int:
        ...
    @property
    def total(self) -> int:
        ...
    @property
    def used(self) -> int:
        ...
def get_cuda_meminfo() -> CUDAMemInfo:
    ...
def get_cuda_memory_free() -> int:
    ...
def get_cuda_memory_total() -> int:
    ...
def get_cuda_memory_used() -> int:
    ...
