"""
Engine module.
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['CameraParams', 'initialize', 'render']
class CameraParams:
    def __init__(self) -> None:
        ...
    @property
    def aperture(self) -> float:
        ...
    @aperture.setter
    def aperture(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def focal_length(self) -> float:
        ...
    @focal_length.setter
    def focal_length(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def focus_distance(self) -> float:
        ...
    @focus_distance.setter
    def focus_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[list[float], "FixedSize(3)"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], "FixedSize(3)"]) -> None:
        ...
    @property
    def resolution(self) -> typing.Annotated[list[int], "FixedSize(2)"]:
        ...
    @resolution.setter
    def resolution(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], "FixedSize(2)"]) -> None:
        ...
    @property
    def rotation(self) -> typing.Annotated[list[float], "FixedSize(3)"]:
        ...
    @rotation.setter
    def rotation(self, arg0: typing.Annotated[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], "FixedSize(3)"]) -> None:
        ...
    @property
    def sensor_width(self) -> float:
        ...
    @sensor_width.setter
    def sensor_width(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def shutter_speed(self) -> float:
        ...
    @shutter_speed.setter
    def shutter_speed(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
def initialize(arg0: CameraParams, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
def render() -> int:
    ...
