"""
Interface module.
"""
from __future__ import annotations
import _pathtracer.core
import _pathtracer.hittable
import _pathtracer.material
import typing
__all__: list[str] = ['SceneInterface']
class SceneInterface:
    def disable(self) -> None:
        ...
    def enable(self) -> None:
        ...
    def get_hit_record(self) -> _pathtracer.hittable.HitRecord:
        ...
    def get_material(self) -> _pathtracer.material.Material:
        ...
    def get_skylight(self) -> Skylight:
        ...
    def get_transform(self) -> _pathtracer.core.Transform:
        ...
    def is_disabled(self) -> bool:
        ...
    def is_enabled(self) -> bool:
        ...
    def query_scene(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def request_skylight_update(self) -> None:
        ...
    def set_material(self, mat: _pathtracer.material.Material) -> None:
        ...
    def set_transform(self, arg0: _pathtracer.core.Transform) -> None:
        ...
    def swap_skylight(self, new_skylight: Skylight) -> None:
        ...
