"""
Interface module.
"""
from __future__ import annotations
import _pathtracer.core
import _pathtracer.hittable
import _pathtracer.material
__all__: list[str] = ['SceneInterface']
class SceneInterface:
    def disable(self) -> None:
        ...
    def get_hit_record(self) -> _pathtracer.hittable.HitRecord:
        ...
    def get_material(self) -> _pathtracer.material.Material:
        ...
    def get_transform(self) -> _pathtracer.core.Transform:
        ...
    def is_enabled(self) -> bool:
        ...
    def set_transform(self, arg0: _pathtracer.core.Transform) -> None:
        ...
    def update_material(self, mat: _pathtracer.material.Material) -> None:
        ...
