"""
Scene module.
"""
from __future__ import annotations
import _pathtracer.core
import _pathtracer.hittable
import _pathtracer.light
import _pathtracer.material
import typing
__all__: list[str] = ['Scene', 'SceneInterface', 'SceneNode', 'SceneOutline']
class Scene:
    def __init__(self, hittables: list, lights: list, skylight: _pathtracer.light.Skylight) -> None:
        ...
class SceneInterface:
    def add_object(self, obj: _pathtracer.hittable.Hittable) -> None:
        ...
    def disable(self) -> None:
        ...
    def enable(self) -> None:
        ...
    def get_hit_record(self) -> _pathtracer.hittable.HitRecord:
        ...
    def get_material(self) -> _pathtracer.material.Material:
        ...
    def get_scene_outline(self) -> SceneOutline:
        ...
    def get_skylight(self) -> _pathtracer.light.Skylight:
        ...
    def get_transform(self) -> _pathtracer.core.Transform:
        ...
    def is_disabled(self) -> bool:
        ...
    def is_enabled(self) -> bool:
        ...
    def query_scene(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def request_skylight_update(self) -> None:
        ...
    def select_scene_node(self, arg0: SceneNode) -> None:
        ...
    def set_material(self, mat: _pathtracer.material.Material) -> None:
        ...
    def set_transform(self, arg0: _pathtracer.core.Transform) -> None:
        ...
    def swap_skylight(self, new_skylight: _pathtracer.light.Skylight) -> None:
        ...
class SceneNode:
    @property
    def material_id(self) -> int:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def object_id(self) -> int:
        ...
    @property
    def parent_id(self) -> int:
        ...
    @property
    def type_name(self) -> str:
        ...
class SceneOutline:
    @property
    def nodes(self) -> list[SceneNode]:
        ...
