"""
Engine module.
"""
from __future__ import annotations
import _pathtracer.data
import _pathtracer.interface
import collections.abc
import typing
from . import camera
from . import denoise
from . import lights
__all__: list[str] = ['EnginePollResponse', 'EngineRequests', 'EngineState', 'RenderEngine', 'Scene', 'camera', 'denoise', 'lights']
class EnginePollResponse:
    camera_params: camera.CameraParams
    should_update_camera: bool
    def __init__(self) -> None:
        ...
class EngineRequests:
    def rebuild_bvh(self) -> None:
        ...
    def restart(self, arg0: bool) -> None:
        ...
    def shutdown(self) -> None:
        ...
    def start(self) -> None:
        ...
    def stop(self) -> None:
        ...
class EngineState:
    """
    Members:
    
      IDLE
    
      RENDERING
    """
    IDLE: typing.ClassVar[EngineState]  # value = <EngineState.IDLE: 0>
    RENDERING: typing.ClassVar[EngineState]  # value = <EngineState.RENDERING: 1>
    __members__: typing.ClassVar[dict[str, EngineState]]  # value = {'IDLE': <EngineState.IDLE: 0>, 'RENDERING': <EngineState.RENDERING: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    @typing.overload
    def __repr__(self) -> str:
        ...
    @typing.overload
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class RenderEngine:
    on_frame_finished: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex], None]
    on_render_finished: collections.abc.Callable[[], None]
    on_render_started: collections.abc.Callable[[], None]
    on_reset: collections.abc.Callable[[], None]
    on_restarted: collections.abc.Callable[[], None]
    on_shutdown: collections.abc.Callable[[], None]
    on_stopped: collections.abc.Callable[[], None]
    poll_updates: collections.abc.Callable[[], EnginePollResponse]
    def __init__(self, camera: camera.Camera, ray_depth: typing.SupportsInt | typing.SupportsIndex = 8, seed: typing.SupportsInt | typing.SupportsIndex = 54321) -> None:
        ...
    def camera(self) -> camera.Camera:
        ...
    def get_scene_interface(self) -> _pathtracer.interface.SceneInterface:
        ...
    def get_state(self) -> EngineState:
        ...
    def idle(self) -> None:
        ...
    def is_idle(self) -> bool:
        ...
    def is_rendering(self) -> bool:
        ...
    def layers(self) -> _pathtracer.data.RenderLayers:
        ...
    def max_depth(self) -> int:
        ...
    def n_samples(self) -> int:
        ...
    def render(self) -> None:
        ...
    def requests(self) -> EngineRequests:
        ...
    def scene(self) -> Scene:
        ...
    def set_max_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_n_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_scene(self, arg0: Scene) -> None:
        ...
    def stream(self) -> _pathtracer.data.TransferStream:
        ...
class Scene:
    def __init__(self, hittables: list, lights: list, skylight: lights.SkyLight) -> None:
        ...
