"""
Engine data submodule.
"""
from __future__ import annotations
import _pathtracer.engine
import typing
__all__: list[str] = ['DataObject', 'RenderLayers', 'RenderLayersConfig', 'TransferStream']
class DataObject:
    def device_ptr(self) -> int:
        ...
    def is_enabled(self) -> bool:
        ...
    def linear_to_gamma(self) -> None:
        ...
    def n_bytes(self) -> int:
        ...
    def n_elements(self) -> int:
        ...
    def n_pixels(self) -> int:
        ...
    def numpy(self) -> numpy.ndarray:
        ...
    def shape(self) -> list[int]:
        ...
    def tonemap(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def C(self) -> int:
        ...
    @property
    def H(self) -> int:
        ...
    @property
    def W(self) -> int:
        ...
class RenderLayers:
    def __init__(self, h: typing.SupportsInt | typing.SupportsIndex = True, w: typing.SupportsInt | typing.SupportsIndex = False, cfg: RenderLayersConfig = False) -> None:
        ...
    def get_layer(self, arg0: _pathtracer.engine.LayerType) -> DataObject:
        ...
    def normalize_by_samples(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def H(self) -> int:
        ...
    @property
    def W(self) -> int:
        ...
    @property
    def beauty(self) -> DataObject:
        ...
    @property
    def depth(self) -> DataObject:
        ...
    @property
    def diffuse(self) -> DataObject:
        ...
    @property
    def emission(self) -> DataObject:
        ...
    @property
    def normal(self) -> DataObject:
        ...
    @property
    def object_id(self) -> DataObject:
        ...
    @property
    def shadow(self) -> DataObject:
        ...
    @property
    def specular(self) -> DataObject:
        ...
class RenderLayersConfig:
    beauty: bool
    depth: bool
    diffuse: bool
    emission: bool
    normal: bool
    object_id: bool
    shadow: bool
    specular: bool
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, beauty: bool = True, diffuse: bool = False, specular: bool = False, normal: bool = False, shadow: bool = False, depth: bool = False, emission: bool = False, object_id: bool = False) -> None:
        ...
class TransferStream:
    def buffer_ptr(self) -> int:
        ...
    def n_bytes(self) -> int:
        ...
    def n_elements(self) -> int:
        ...
    def n_pixels(self) -> int:
        ...
    def readback(self) -> int:
        ...
    def shape(self) -> typing.Annotated[list[int], "FixedSize(3)"]:
        ...
